### ISSUE TITLE
Scorum Network transactions

### ISSUE THREAD

**Issue by mglinnik** [EZStaking/app-registry#2]
Hello
Would like to know why the list of transactions is not displayed for this network (https://ezstaking.app/scorum) and how to make them start appearing there? Thanks!

**Comment by zakarialounes** [comment]
@mglinnik only recent transactions are displayed, and the tab must be in focus state, otherwise blocks are not longer loaded and therefore neither are transactions. This is to avoid numerous connections with inactive tabs.
