### ISSUE TITLE
Scorum coingecko price chart

### ISSUE THREAD

**Issue by mglinnik** [EZStaking/app-registry#7]
Good day!

I see that after adding the coingeko ID for scorum, the price chart and price information did not appear on the network page on ezstaking. Can you advise if there are any additional changes that need to be added? Thank you!
https://ezstaking.app/scorum

**Comment by zakarialounes** [comment]
Any change to the app-registery requires us to re-build the app. We've just released a patch for something else (and re-building the app right now), so your chart should appear shortly.

**Comment by mglinnik** [comment]
Noted, thank you @zakarialounes

**Comment by zakarialounes** [comment]
Could you please update your [discord invitation](https://github.com/ezstaking/app-registry/blob/216ac0f588eb2f830ff068ec8980fb65c2ff7479/chains/mainnets/scorum/chain.json#L74) and make sure there is no date limit? You can create a PR if you need to update the link. Thanks in advance @mglinnik
